import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { createEntity, deleteEntity, listEntities, updateEntity } from '../lib/core'
import { useWorkspace } from '../lib/workspace'

const TABS=[['overview','Overview'],['crm','CRM'],['marketing','Marketing'],['seo','SEO'],['affiliate','Affiliate'],['digital','Digital Products'],['creator','Creator Business'],['existing','Existing Modules']]

function CrudPanel({title,table,workspaceId,projectId,fields,initial}){
  const [rows,setRows]=useState([]),[value,setValue]=useState({...initial,...(projectId?{project_id:projectId}:{})}),[editing,setEditing]=useState(null),[error,setError]=useState('')
  const load=async()=>{if(!workspaceId)return;try{const all=await listEntities(table,workspaceId);setRows(projectId?all.filter(x=>x.project_id===projectId||!x.project_id):all)}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[workspaceId,projectId])
  function reset(){setEditing(null);setValue({...initial,...(projectId?{project_id:projectId}:{})})}
  async function save(e){e.preventDefault();setError('');try{const payload={...value};for(const [k,,type] of fields)if(type==='number')payload[k]=payload[k]===''?null:Number(payload[k]);if(editing)await updateEntity(table,editing,payload);else await createEntity(table,{workspace_id:workspaceId,...payload});reset();load()}catch(e){setError(e.message)}}
  async function remove(id){if(!window.confirm('حذف السجل؟'))return;try{await deleteEntity(table,id);load()}catch(e){setError(e.message)}}
  return <div className="card"><div className="section-head"><h3>{title}</h3>{editing&&<button className="secondary" type="button" onClick={reset}>إلغاء</button>}</div>{error&&<div className="error">{error}</div>}<form className="form-grid" onSubmit={save}>{fields.map(([key,label,type='text',options])=>type==='select'?<select key={key} value={value[key]??''} onChange={e=>setValue(v=>({...v,[key]:e.target.value}))}><option value="">{label}</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input key={key} type={type} placeholder={label} value={value[key]??''} onChange={e=>setValue(v=>({...v,[key]:e.target.value}))}/>)}<button className="primary">{editing?'حفظ':'إضافة'}</button></form><div style={{marginTop:12}}>{rows.slice(0,12).map(row=><div className="list-row between" key={row.id}><div><strong>{row.name||row.title||row.keyword||row.label||row.brand}</strong><div className="muted">{row.status||row.stage||row.channel||row.description||row.notes||''}</div></div><div className="actions"><button className="secondary" onClick={()=>{const next={};fields.forEach(([k])=>next[k]=row[k]??'');setEditing(row.id);setValue(next)}}>تعديل</button><button className="danger" onClick={()=>remove(row.id)}>حذف</button></div></div>)}{!rows.length&&<div className="muted">لا توجد سجلات.</div>}</div></div>
}

export default function BusinessOS(){
  const {id:projectId}=useParams();const {workspace}=useWorkspace();const [tab,setTab]=useState('overview');const [summary,setSummary]=useState({customers:[],campaigns:[],keywords:[],programs:[],digital:[],creator:[]});const [error,setError]=useState('')
  useEffect(()=>{if(!workspace)return;const tables=['uos_business_customers','uos_business_marketing_campaigns','uos_business_seo_keywords','uos_business_affiliate_programs','uos_business_digital_products','uos_business_creator_sponsorships'];Promise.all(tables.map(t=>listEntities(t,workspace.id))).then(r=>setSummary({customers:r[0],campaigns:r[1],keywords:r[2],programs:r[3],digital:r[4],creator:r[5]})).catch(e=>setError(e.message))},[workspace?.id])
  const scoped=k=>projectId?summary[k].filter(x=>x.project_id===projectId||!x.project_id):summary[k]
  const stats=useMemo(()=>({crm:scoped('customers').length,marketing:scoped('campaigns').length,seo:scoped('keywords').length,affiliate:scoped('programs').length,digital:scoped('digital').length,creator:scoped('creator').length}),[summary,projectId])
  if(!workspace)return <div className="card">Loading…</div>
  return <div><header className="page-head"><div><div className="eyebrow">BUSINESS OS · MODULAR</div><h1>Business OS</h1><p className="muted">Business Area هو aggregation layer فوق Projects. كل module يتفعل على مستوى المشروع، وContentOS يظل subsystem مستقلًا.</p><div className="chip-row"><span className="chip selected">{projectId?'Project-scoped':'Workspace-wide'}</span><span className="chip">Shared Finance Ledger</span><span className="chip">No duplicate ContentOS</span></div></div><div className="actions"><Link className="primary" to={projectId?`/projects/${projectId}`:'/projects'}>Projects</Link>{projectId&&<Link className="secondary" to={`/projects/${projectId}/contentos`}>ContentOS</Link>}</div></header>{error&&<div className="error">{error}</div>}
  <div className="tabs">{TABS.map(([k,l])=><button key={k} className={`chip ${tab===k?'selected':''}`} onClick={()=>setTab(k)}>{l}</button>)}</div>
  {tab==='overview'&&<section className="section"><div className="grid grid-3">{[['crm','CRM','Customer lifecycle'],['marketing','Marketing','CTR / CPC / CPA / ROAS'],['seo','SEO','Keywords + tasks + snapshots'],['affiliate','Affiliate','Programs + links + conversions'],['digital','Digital Products','Products + assets + versions + sales'],['creator','Creator Business','Sponsorships + ContentOS + Finance']].map(([k,t,d])=><div className="card" key={k}><div className="eyebrow">{t}</div><strong>{stats[k]}</strong><div className="muted">{d}</div><button className="secondary" style={{marginTop:10}} onClick={()=>setTab(k)}>Open</button></div>)}</div><div className="section grid grid-3"><Link className="card hover" to={projectId?`/projects/${projectId}/product`:'/product'}>Product / SaaS → existing Product OS</Link><Link className="card hover" to={projectId?`/projects/${projectId}/commerce`:'/commerce'}>E-commerce → existing Commerce OS</Link><Link className="card hover" to={projectId?`/projects/${projectId}/marketplace`:'/marketplace'}>Marketplace → existing Marketplace OS</Link></div></section>}
  {tab==='crm'&&<CrudPanel title="CRM Customers" table="uos_business_customers" workspaceId={workspace.id} projectId={projectId} fields={[["name","Customer name"],["email","Email","email"],["phone","Phone"],["company","Company"],["stage","Stage","select",['new','contacted','qualified','proposal','negotiation','won','lost']],["next_follow_up_at","Next follow-up","datetime-local"]]} initial={{name:'',email:'',phone:'',company:'',stage:'new',next_follow_up_at:''}}/>}
  {tab==='marketing'&&<CrudPanel title="Marketing Campaigns" table="uos_business_marketing_campaigns" workspaceId={workspace.id} projectId={projectId} fields={[["name","Campaign name"],["channel","Channel"],["audience","Audience"],["spend","Spend","number"],["clicks","Clicks","number"],["impressions","Impressions","number"],["conversions","Conversions","number"],["revenue","Revenue","number"],["status","Status","select",['draft','active','paused','completed']]]} initial={{name:'',channel:'',audience:'',spend:'',clicks:'',impressions:'',conversions:'',revenue:'',status:'draft'}}/>}
  {tab==='seo'&&<div className="grid grid-2"><CrudPanel title="SEO Keywords" table="uos_business_seo_keywords" workspaceId={workspace.id} projectId={projectId} fields={[["keyword","Keyword"],["intent","Intent"],["search_volume","Search volume","number"],["difficulty","Difficulty","number"],["target_url","Target URL","url"],["status","Status","select",['research','target','ranking','archived']]]} initial={{keyword:'',intent:'',search_volume:'',difficulty:'',target_url:'',status:'research'}}/><CrudPanel title="SEO Content" table="uos_business_seo_content" workspaceId={workspace.id} projectId={projectId} fields={[["title","Title"],["content_url","URL","url"],["status","Status","select",['draft','published','refresh','archived']]]} initial={{title:'',content_url:'',status:'draft'}}/></div>}
  {tab==='affiliate'&&<div className="grid grid-2"><CrudPanel title="Affiliate Programs" table="uos_business_affiliate_programs" workspaceId={workspace.id} projectId={projectId} fields={[["name","Program name"],["network","Network"],["terms","Terms"],["status","Status","select",['active','paused','closed']]]} initial={{name:'',network:'',terms:'',status:'active'}}/><CrudPanel title="Affiliate Payouts" table="uos_business_affiliate_payouts" workspaceId={workspace.id} projectId={projectId} fields={[["amount","Amount","number"],["paid_at","Paid at","date"],["status","Status","select",['pending','paid','failed']],["notes","Notes"]]} initial={{amount:'',paid_at:'',status:'pending',notes:''}}/></div>}
  {tab==='digital'&&<div className="grid grid-2"><CrudPanel title="Digital Products" table="uos_business_digital_products" workspaceId={workspace.id} projectId={projectId} fields={[["name","Product name"],["description","Description"],["price","Price","number"],["currency","Currency"],["status","Status","select",['draft','active','archived']]]} initial={{name:'',description:'',price:'',currency:'EGP',status:'draft'}}/><CrudPanel title="Digital Versions" table="uos_business_digital_versions" workspaceId={workspace.id} projectId={projectId} fields={[["version","Version"],["changelog","Changelog"],["released_at","Release date","date"],["status","Status","select",['draft','released','retired']]]} initial={{version:'',changelog:'',released_at:'',status:'draft'}}/></div>}
  {tab==='creator'&&<CrudPanel title="Creator Sponsorships" table="uos_business_creator_sponsorships" workspaceId={workspace.id} projectId={projectId} fields={[["brand","Brand"],["deliverable","Deliverable"],["status","Status","select",['lead','negotiating','contracted','delivered','paid','closed']],["agreed_fee","Agreed fee","number"],["start_date","Start","date"],["end_date","End","date"],["notes","Notes"]]} initial={{brand:'',deliverable:'',status:'lead',agreed_fee:'',start_date:'',end_date:'',notes:''}}/>}
  {tab==='existing'&&<section className="section grid grid-3"><Link className="card hover" to={projectId?`/projects/${projectId}/product`:'/product'}>Product / SaaS</Link><Link className="card hover" to={projectId?`/projects/${projectId}/commerce`:'/commerce'}>E-commerce</Link><Link className="card hover" to={projectId?`/projects/${projectId}/marketplace`:'/marketplace'}>Marketplace</Link><Link className="card hover" to="/contentos">ContentOS (source of truth)</Link><Link className="card hover" to="/finance">Finance Ledger</Link></section>}
  </div>
}
