import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { createEntity, deleteEntity, listEntities, updateEntity } from '../lib/core'
import { useWorkspace } from '../lib/workspace'

const TABS=[['overview','Overview'],['crm','CRM'],['marketing','Marketing'],['seo','SEO'],['affiliate','Affiliate'],['digital','Digital Products'],['creator','Creator Business'],['existing','Product · Commerce · Marketplace']]
const money=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:0})
function Card({title,children,actions}){return <section className="card business-card"><div className="section-head"><h3>{title}</h3>{actions}</div>{children}</section>}
function Metric({label,value,sub}){return <div className="metric"><div className="muted">{label}</div><strong>{value}</strong>{sub&&<div className="muted">{sub}</div>}</div>}
function Status({children}){return <span className="status-badge info">{children}</span>}
function Empty({text='No records yet.'}){return <div className="empty-state"><span>○</span><div>{text}</div></div>}

const tables=['uos_business_customers','uos_business_customer_stage_history','uos_business_marketing_campaigns','uos_business_seo_keywords','uos_business_seo_content','uos_business_seo_tasks','uos_business_seo_snapshots','uos_business_affiliate_programs','uos_business_affiliate_merchants','uos_business_affiliate_links','uos_business_affiliate_conversions','uos_business_affiliate_payouts','uos_business_digital_products','uos_business_digital_assets','uos_business_digital_versions','uos_business_digital_platforms','uos_business_digital_sales','uos_business_digital_refunds','uos_business_creator_sponsorships']
function useBusinessData(workspaceId,projectId){const [data,setData]=useState(Object.fromEntries(tables.map(t=>[t,[]]))),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=async()=>{if(!workspaceId)return;setBusy(true);try{const rows=await Promise.all(tables.map(t=>listEntities(t,workspaceId)));const next=Object.fromEntries(tables.map((t,i)=>{const child=['uos_business_digital_assets','uos_business_digital_versions','uos_business_digital_platforms','uos_business_digital_sales','uos_business_digital_refunds'].includes(t);return [t,projectId&&!child?(rows[i]||[]).filter(x=>x.project_id===projectId||!x.project_id):(rows[i]||[])]}));setData(next)}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[workspaceId,projectId]);return {data,error,busy,load}}

function Crud({table,workspaceId,projectId,title,fields,compact=false}){const [rows,setRows]=useState([]),[v,setV]=useState({}),[editing,setEditing]=useState(null),[error,setError]=useState('');useEffect(()=>{setV(Object.fromEntries(fields.map(f=>[f[0],f[4]??''])))},[title]);const projectFree=['uos_business_digital_assets','uos_business_digital_versions','uos_business_digital_platforms','uos_business_digital_sales','uos_business_digital_refunds'].includes(table);const load=async()=>{try{const all=await listEntities(table,workspaceId);setRows(projectFree?all:(projectId?all.filter(x=>x.project_id===projectId||!x.project_id):all))}catch(e){setError(e.message)}};useEffect(()=>{load()},[workspaceId,projectId]);const save=async e=>{e.preventDefault();setError('');try{const payload={...v};fields.forEach(([k,,type])=>{if(type==='number')payload[k]=payload[k]===''?null:Number(payload[k])});if(editing)await updateEntity(table,editing,payload);else await createEntity(table,projectFree?{workspace_id:workspaceId,...payload}:{workspace_id:workspaceId,project_id:projectId||null,...payload});setEditing(null);setV(Object.fromEntries(fields.map(f=>[f[0],f[4]??''])));load()}catch(err){setError(err.message)}};const remove=async id=>{if(!confirm('Delete this record?'))return;try{await deleteEntity(table,id);load()}catch(err){setError(err.message)}};return <Card title={title} actions={editing&&<button className="secondary" onClick={()=>{setEditing(null);setV(Object.fromEntries(fields.map(f=>[f[0],f[4]??''])) )}}>Cancel</button>}>{error&&<div className="error">{error}</div>}<form className={compact?'business-form compact':'business-form'} onSubmit={save}>{fields.map(([k,l,type='text',options,def])=>type==='select'?<select key={k} value={v[k]??''} onChange={e=>setV(x=>({...x,[k]:e.target.value}))}><option value="">{l}</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>:type==='textarea'?<textarea key={k} placeholder={l} value={v[k]??''} onChange={e=>setV(x=>({...x,[k]:e.target.value}))}/>:<input key={k} type={type} placeholder={l} value={v[k]??''} onChange={e=>setV(x=>({...x,[k]:e.target.value}))}/>) }<button className="primary">{editing?'Save':'Add'}</button></form><div className="business-record-list">{rows.slice(0,16).map(row=><div className="business-record" key={row.id}><div><strong>{row.name||row.title||row.keyword||row.label||row.brand||row.customer}</strong><div className="muted">{row.status||row.stage||row.channel||row.description||row.notes||''}</div></div><div className="actions"><button className="secondary" onClick={()=>{setEditing(row.id);setV(Object.fromEntries(fields.map(f=>[f[0],row[f[0]]??''])))}}>Edit</button><button className="danger" onClick={()=>remove(row.id)}>Delete</button></div></div>)}{!rows.length&&<Empty/>}</div></Card>}

export default function BusinessOS(){const {id:projectId}=useParams();const {workspace}=useWorkspace();const [tab,setTab]=useState('overview');const {data,error,busy,load}=useBusinessData(workspace?.id,projectId);if(!workspace)return <div className="card">Loading Business OS…</div>;const scoped=t=>data[t]||[];const campaigns=scoped('uos_business_marketing_campaigns');const customers=scoped('uos_business_customers');const digitalSales=scoped('uos_business_digital_sales');const affiliateConv=scoped('uos_business_affiliate_conversions');const marketing={spend:campaigns.reduce((s,x)=>s+Number(x.spend||0),0),clicks:campaigns.reduce((s,x)=>s+Number(x.clicks||0),0),impressions:campaigns.reduce((s,x)=>s+Number(x.impressions||0),0),conversions:campaigns.reduce((s,x)=>s+Number(x.conversions||0),0),revenue:campaigns.reduce((s,x)=>s+Number(x.revenue||0),0)};const ctr=marketing.impressions?marketing.clicks/marketing.impressions*100:0;const cpc=marketing.clicks?marketing.spend/marketing.clicks:0;const cpa=marketing.conversions?marketing.spend/marketing.conversions:0;const roas=marketing.spend?marketing.revenue/marketing.spend:0;const stages=['new','contacted','qualified','proposal','negotiation','won'];return <div className="business-os"><header className="page-head"><div><div className="eyebrow">BUSINESS OS · MODULAR</div><h1>Business OS</h1><p className="muted">One business workspace across CRM, growth, commerce, product and creator revenue.</p><div className="chip-row"><span className="chip selected">{projectId?'Project scoped':'Workspace wide'}</span><span className="chip">Shared Finance Ledger</span><span className="chip">Modules stay contextual to Projects</span></div></div><div className="actions"><Link className="primary" to={projectId?`/projects/${projectId}`:'/projects'}>Projects</Link>{projectId&&<Link className="secondary" to={`/projects/${projectId}/contentos`}>ContentOS</Link>}<button className="secondary" onClick={load}>{busy?'Refreshing…':'Refresh'}</button></div></header>{error&&<div className="error">{error}</div>}<div className="business-tabs">{TABS.map(([k,l])=><button className={`fitness-tab ${tab===k?'active':''}`} key={k} onClick={()=>setTab(k)}>{l}</button>)}</div>
 {tab==='overview'&&<Overview stats={{customers:customers.length,campaigns:campaigns.length,keywords:scoped('uos_business_seo_keywords').length,digital:scoped('uos_business_digital_products').length,creator:scoped('uos_business_creator_sponsorships').length,sales:digitalSales.length,conversions:affiliateConv.length}} marketing={{ctr,cpc,cpa,roas}} stages={stages} customers={customers} setTab={setTab}/>} 
 {tab==='crm'&&<CRMView workspaceId={workspace.id} projectId={projectId} data={data} load={load}/>} 
 {tab==='marketing'&&<MarketingView workspaceId={workspace.id} projectId={projectId} data={data} load={load}/>} 
 {tab==='seo'&&<SEOView workspaceId={workspace.id} projectId={projectId} data={data} load={load}/>} 
 {tab==='affiliate'&&<AffiliateView workspaceId={workspace.id} projectId={projectId} data={data} load={load}/>} 
 {tab==='digital'&&<DigitalView workspaceId={workspace.id} projectId={projectId} data={data} load={load}/>} 
 {tab==='creator'&&<CreatorView workspaceId={workspace.id} projectId={projectId} data={data} load={load}/>} 
 {tab==='existing'&&<ExistingModules projectId={projectId}/>} </div>}

function Overview({stats,marketing,stages,customers,setTab}){return <section className="section"><div className="business-kpi-grid"><Metric label="CRM pipeline" value={stats.customers}/><Metric label="Campaigns" value={stats.campaigns}/><Metric label="Marketing CTR" value={`${marketing.ctr.toFixed(2)}%`}/><Metric label="ROAS" value={`${marketing.roas.toFixed(2)}×`}/><Metric label="Digital sales" value={stats.sales}/><Metric label="Affiliate conversions" value={stats.conversions}/></div><div className="business-overview-grid section"><Card title="Go-to-market control center"><div className="quick-module-grid">{[['crm','CRM','Lead → Won/Lost'],['marketing','Marketing','Spend → Revenue'],['seo','SEO','Keyword → Content → Snapshot'],['affiliate','Affiliate','Program → Link → Conversion'],['digital','Digital Products','Product → Version → Sale'],['creator','Creator Business','Sponsor → Deliverable → Finance']].map(([k,t,d])=><button className="module-tile" key={k} onClick={()=>setTab(k)}><span className="eyebrow">{t}</span><strong>{d}</strong><small>Open workspace →</small></button>)}</div></Card><Card title="CRM pipeline"><div className="pipeline-grid">{stages.map(s=><div className="pipeline-column" key={s}><div className="pipeline-head"><span>{s}</span><strong>{customers.filter(c=>c.stage===s).length}</strong></div>{customers.filter(c=>c.stage===s).slice(0,5).map(c=><div className="pipeline-card" key={c.id}><strong>{c.name}</strong><span>{c.company||c.email||'No company'}</span></div>)}</div>)}</div></Card></div></section>}

function CRMView({workspaceId,projectId,data,load}){return <section className="section"><div className="grid grid-2"><Crud table="uos_business_customers" workspaceId={workspaceId} projectId={projectId} title="CRM · Customer records" fields={[["name","Customer name"],["email","Email","email"],["phone","Phone"],["company","Company"],["stage","Stage","select",['new','contacted','qualified','proposal','negotiation','won','lost']],['source','Source'],['next_follow_up_at','Next follow-up','datetime-local'],['notes','Notes','textarea']]}/><Card title="Lifecycle"><div className="muted">Stage changes are written to stage history by the database trigger.</div><div className="section-list">{data.uos_business_customer_stage_history?.slice(0,12).map(h=><div className="list-row" key={h.id}>{h.from_stage||'—'} → <strong>{h.to_stage}</strong><div className="muted">{new Date(h.changed_at).toLocaleString('en-GB')}</div></div>)}</div></Card></div></section>}

function MarketingView({workspaceId,projectId,data,load}){const campaigns=data.uos_business_marketing_campaigns;const metrics={spend:campaigns.reduce((s,x)=>s+Number(x.spend||0),0),clicks:campaigns.reduce((s,x)=>s+Number(x.clicks||0),0),impressions:campaigns.reduce((s,x)=>s+Number(x.impressions||0),0),conversions:campaigns.reduce((s,x)=>s+Number(x.conversions||0),0),revenue:campaigns.reduce((s,x)=>s+Number(x.revenue||0),0)};return <section className="section"><div className="business-kpi-grid compact"><Metric label="CTR" value={`${(metrics.impressions?metrics.clicks/metrics.impressions*100:0).toFixed(2)}%`}/><Metric label="CPC" value={money(metrics.clicks?metrics.spend/metrics.clicks:0)}/><Metric label="CPA" value={money(metrics.conversions?metrics.spend/metrics.conversions:0)}/><Metric label="ROAS" value={`${(metrics.spend?metrics.revenue/metrics.spend:0).toFixed(2)}×`}/></div><div className="section grid grid-2"><Crud table="uos_business_marketing_campaigns" workspaceId={workspaceId} projectId={projectId} title="Campaign planner" fields={[["name","Campaign name"],["channel","Channel"],["audience","Audience"],["creative","Creative"],["spend","Spend","number"],["impressions","Impressions","number"],["clicks","Clicks","number"],["conversions","Conversions","number"],["revenue","Revenue","number"],["status","Status","select",['draft','active','paused','completed']]]}/><Card title="Campaign health"><div className="metric-list"><div><span>Spend</span><strong>{money(metrics.spend)}</strong></div><div><span>Revenue</span><strong>{money(metrics.revenue)}</strong></div><div><span>Conversions</span><strong>{metrics.conversions}</strong></div></div></Card></div></section>}

function SEOView({workspaceId,projectId,data,load}){return <section className="section"><div className="grid grid-2"><Crud table="uos_business_seo_keywords" workspaceId={workspaceId} projectId={projectId} title="Keyword research" fields={[["keyword","Keyword"],["intent","Intent"],["search_volume","Search volume","number"],["difficulty","Difficulty","number"],["target_url","Target URL","url"],["status","Status","select",['research','target','ranking','archived']]]}/><Crud table="uos_business_seo_content" workspaceId={workspaceId} projectId={projectId} title="Content library" fields={[["title","Content title"],["content_url","URL","url"],["keyword_id","Keyword ID"],["status","Status","select",['draft','published','refresh','archived']]]}/><Crud table="uos_business_seo_tasks" workspaceId={workspaceId} projectId={projectId} title="SEO task queue" fields={[["title","Task"],["type","Type"],["status","Status","select",['todo','in_progress','done']],["due_date","Due date","date"]]}/><Crud table="uos_business_seo_snapshots" workspaceId={workspaceId} projectId={projectId} title="Performance snapshots" fields={[["keyword_id","Keyword ID"],["captured_at","Captured at","date"],["position","Position","number"],["clicks","Clicks","number"],["impressions","Impressions","number"],["ctr","CTR","number"]]}/></div></section>}

function AffiliateView({workspaceId,projectId,data,load}){return <section className="section"><div className="grid grid-2"><Crud table="uos_business_affiliate_programs" workspaceId={workspaceId} projectId={projectId} title="Affiliate programs" fields={[["name","Program"],["network","Network"],["terms","Terms","textarea"],["status","Status","select",['active','paused','closed']]]}/><Crud table="uos_business_affiliate_merchants" workspaceId={workspaceId} projectId={projectId} title="Merchants" fields={[["name","Merchant"],["program_id","Program ID"],["website","Website","url"],["commission_rate","Commission %","number"],["status","Status","select",['active','paused','closed']]]}/><Crud table="uos_business_affiliate_links" workspaceId={workspaceId} projectId={projectId} title="Tracking links" fields={[["label","Link label"],["merchant_id","Merchant ID"],["tracking_url","Tracking URL","url"],["external_id","External ID"]]}/><Crud table="uos_business_affiliate_conversions" workspaceId={workspaceId} projectId={projectId} title="Conversions" fields={[["link_id","Link ID"],["order_ref","Order ref"],["revenue","Revenue","number"],["commission","Commission","number"],["status","Status","select",['pending','approved','reversed']]]}/><Crud table="uos_business_affiliate_payouts" workspaceId={workspaceId} projectId={projectId} title="Payouts" fields={[["program_id","Program ID"],["amount","Amount","number"],["paid_at","Paid at","date"],["status","Status","select",['pending','paid','failed']],["notes","Notes","textarea"]]}/></div></section>}

function DigitalView({workspaceId,projectId,data,load}){return <section className="section"><div className="grid grid-2"><Crud table="uos_business_digital_products" workspaceId={workspaceId} projectId={projectId} title="Products" fields={[["name","Product name"],["description","Description","textarea"],["price","Price","number"],["currency","Currency"],["status","Status","select",['draft','active','archived']]]}/><Crud table="uos_business_digital_versions" workspaceId={workspaceId} projectId={projectId} title="Versions" fields={[["product_id","Product ID"],["version","Version"],["changelog","Changelog","textarea"],["released_at","Release date","date"],["status","Status","select",['draft','released','retired']]]}/><Crud table="uos_business_digital_assets" workspaceId={workspaceId} projectId={projectId} title="Assets" fields={[["product_id","Product ID"],["name","Asset name"],["asset_type","Type"],["url","URL","url"]]}/><Crud table="uos_business_digital_platforms" workspaceId={workspaceId} projectId={projectId} title="Platforms" fields={[["product_id","Product ID"],["name","Platform"],["url","URL","url"],["status","Status","select",['active','paused','closed']]]}/><Crud table="uos_business_digital_sales" workspaceId={workspaceId} projectId={projectId} title="Sales" fields={[["product_id","Product ID"],["platform_id","Platform ID"],["customer","Customer"],["amount","Amount","number"],["currency","Currency"],["external_id","External ID"]]}/><Crud table="uos_business_digital_refunds" workspaceId={workspaceId} projectId={projectId} title="Refunds" fields={[["sale_id","Sale ID"],["amount","Amount","number"],["reason","Reason"],["status","Status","select",['requested','approved','processed','rejected']]]}/></div></section>}

function CreatorView({workspaceId,projectId}){return <section className="section"><div className="grid grid-2"><Crud table="uos_business_creator_sponsorships" workspaceId={workspaceId} projectId={projectId} title="Sponsorship pipeline" fields={[["brand","Brand"],["deliverable","Deliverable"],["status","Status","select",['lead','negotiating','contracted','delivered','paid','closed']],["agreed_fee","Fee","number"],["currency","Currency"],["start_date","Start","date"],["end_date","End","date"],["notes","Notes","textarea"]]}/><Card title="Creator business connections"><div className="connection-grid"><Link className="module-tile" to={projectId?`/projects/${projectId}/contentos`:'/contentos'}><strong>ContentOS</strong><small>Publishing + analytics source of truth</small></Link><Link className="module-tile" to="/finance"><strong>Finance</strong><small>Revenue + ledger + transactions</small></Link><Link className="module-tile" to={projectId?`/projects/${projectId}/commerce`:'/commerce'}><strong>Commerce</strong><small>Offers + inventory + orders</small></Link></div></Card></div></section>}

function ExistingModules({projectId}){const links=[['Product / SaaS',projectId?`/projects/${projectId}/product`:'/product'],['E-commerce',projectId?`/projects/${projectId}/commerce`:'/commerce'],['Marketplace',projectId?`/projects/${projectId}/marketplace`:'/marketplace'],['ContentOS',projectId?`/projects/${projectId}/contentos`:'/contentos'],['Finance','/finance']];return <section className="section"><div className="grid grid-3">{links.map(([t,h])=><Link className="card hover" key={h} to={h}><div className="eyebrow">OPEN SYSTEM</div><h3>{t}</h3><p className="muted">Open the existing source-of-truth surface; no duplicate data layer is created here.</p></Link>)}</div></section>}
