import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { createEntity, deleteEntity, listEntities } from '../lib/core'
import { useWorkspace } from '../lib/workspace'

const STATUSES=['done','partial','missed','skipped']
function weekStart(){ const d=new Date(); const day=(d.getDay()+6)%7; d.setDate(d.getDate()-day); return d.toISOString().slice(0,10) }
function weekEnd(){ const d=new Date(weekStart()); d.setDate(d.getDate()+6); return d.toISOString().slice(0,10) }

export default function Habits(){
 const {id:projectId}=useParams(); const {workspace}=useWorkspace()
 const [rows,setRows]=useState([]),[logs,setLogs]=useState([]),[reviews,setReviews]=useState([]),[error,setError]=useState('')
 const [log,setLog]=useState({}),[form,setForm]=useState({name:'',type:'boolean',frequency:'daily',target:'',category:'',start_date:'',goal:''})
 const [review,setReview]=useState({summary:'',wins:'',misses:'',blockers:'',next_focus:''})
 async function load(){if(!workspace)return;try{const [h,l,r]=await Promise.all([listEntities('uos_habits',workspace.id),listEntities('uos_habit_logs',workspace.id,'log_date'),listEntities('uos_habit_weekly_reviews',workspace.id,'week_start')]);setRows(projectId?h.filter(x=>x.project_id===projectId||!x.project_id):h);setLogs(l);setReviews(projectId?r.filter(x=>x.project_id===projectId||!x.project_id):r);setLog(Object.fromEntries(l.filter(x=>x.log_date===new Date().toISOString().slice(0,10)).map(x=>[x.habit_id,x.status])))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[workspace?.id,projectId])
 async function submit(e){e.preventDefault();try{await createEntity('uos_habits',{workspace_id:workspace.id,project_id:projectId||null,...form,target:form.target?Number(form.target):null});setForm({name:'',type:'boolean',frequency:'daily',target:'',category:'',start_date:'',goal:''});load()}catch(e){setError(e.message)}}
 async function mark(h,status){try{const today=new Date().toISOString().slice(0,10);const existing=logs.find(x=>x.habit_id===h.id&&x.log_date===today);if(existing) await (await import('../lib/core')).updateEntity('uos_habit_logs',existing.id,{status,actual_value:h.target||1});else await createEntity('uos_habit_logs',{workspace_id:workspace.id,project_id:projectId||null,habit_id:h.id,log_date:today,status,actual_value:h.target||1});load()}catch(e){setError(e.message)}}
 async function saveReview(e){e.preventDefault();try{await createEntity('uos_habit_weekly_reviews',{workspace_id:workspace.id,project_id:projectId||null,week_start:weekStart(),week_end:weekEnd(),...review});setReview({summary:'',wins:'',misses:'',blockers:'',next_focus:''});load()}catch(e){setError(e.message)}}
 const completion=useMemo(()=>{const mine=logs.filter(l=>rows.some(h=>h.id===l.habit_id)); return {done:mine.filter(l=>l.status==='done').length, total:mine.length}},[logs,rows])
 return <div><header className="page-head"><div><div className="eyebrow">PERSONAL OS · HABIT</div><h1>Habits</h1><p className="muted">Habit Master + Daily Log + Weekly Review. العادة ليست Task.</p><div className="chip-row"><span className="chip selected">{projectId?'Project-scoped':'Workspace-wide'}</span><span className="chip">Today: {completion.done}/{completion.total || rows.length} done</span></div></div></header>{error&&<div className="error">{error}</div>}
 <div className="card"><form onSubmit={submit}><div className="form-grid"><input placeholder="العادة" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option>daily</option><option>weekly</option><option>custom</option></select><input placeholder="الهدف" type="number" value={form.target} onChange={e=>setForm({...form,target:e.target.value})}/><input placeholder="الفئة" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input placeholder="تاريخ البداية" type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/><input placeholder="الهدف الأكبر" value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/><button className="primary">إضافة</button></div></form></div>
 <section className="section"><div className="grid grid-2">{rows.map(h=><div className="card" key={h.id}><div className="between"><strong>{h.name}</strong><button className="danger" onClick={()=>deleteEntity('uos_habits',h.id).then(load)}>حذف</button></div><div className="muted">{h.frequency} · {h.category||'بدون فئة'}{h.goal?` · ${h.goal}`:''}</div><div className="actions" style={{marginTop:10}}>{STATUSES.map(s=><button key={s} className="secondary" onClick={()=>mark(h,s)}>{s}</button>)}<span className="chip">{log[h.id]||'لم يسجل اليوم'}</span></div></div>)}{!rows.length&&<div className="card muted">لا توجد عادات بعد.</div>}</div></section>
 <section className="section grid grid-2"><div className="card"><h3>Weekly Review</h3><form className="form-stack" onSubmit={saveReview}><textarea rows="2" placeholder="ملخص الأسبوع" value={review.summary} onChange={e=>setReview({...review,summary:e.target.value})}/><textarea rows="2" placeholder="Wins" value={review.wins} onChange={e=>setReview({...review,wins:e.target.value})}/><textarea rows="2" placeholder="Misses" value={review.misses} onChange={e=>setReview({...review,misses:e.target.value})}/><textarea rows="2" placeholder="Blockers" value={review.blockers} onChange={e=>setReview({...review,blockers:e.target.value})}/><textarea rows="2" placeholder="Next focus" value={review.next_focus} onChange={e=>setReview({...review,next_focus:e.target.value})}/><button className="primary">حفظ مراجعة الأسبوع</button></form></div><div className="card"><h3>Recent Reviews</h3>{reviews.slice(0,8).map(r=><div className="list-row" key={r.id}><strong>{r.week_start} → {r.week_end}</strong><div className="muted">{r.summary||r.next_focus||'بدون ملخص'}</div></div>)}{!reviews.length&&<div className="muted">لا توجد مراجعات أسبوعية بعد.</div>}</div></section>
 </div>
}
