import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { createEntity, deleteEntity, listEntities } from '../lib/core'
import { useWorkspace } from '../lib/workspace'

const SESSION_STATUSES=['planned','in_progress','completed','skipped','cancelled']

export default function Learning(){
  const {id: projectId}=useParams(); const {workspace}=useWorkspace()
  const [courses,setCourses]=useState([]),[modules,setModules]=useState([]),[lessons,setLessons]=useState([]),[skills,setSkills]=useState([]),[sessions,setSessions]=useState([]),[resources,setResources]=useState([])
  const [course,setCourse]=useState({title:'',skill_id:'',description:'',status:'active'}),[module,setModule]=useState({title:'',course_id:'',sort_order:'0'}),[lesson,setLesson]=useState({title:'',course_id:'',module_id:'',duration_minutes:'',watched_minutes:'',skill_id:'',resource_id:'',status:'not_started'}),[skill,setSkill]=useState({name:'',category:'',target_level:'',current_level:'0'}),[session,setSession]=useState({course_id:'',lesson_id:'',skill_id:'',scheduled_at:'',duration_minutes:'',actual_minutes:'0',status:'planned',notes:''})
  const [error,setError]=useState('')

  async function load(){
    if(!workspace)return
    try{
      const [c,m,l,s,ss,r]=await Promise.all([listEntities('uos_learning_courses',workspace.id),listEntities('uos_learning_modules',workspace.id),listEntities('uos_learning_lessons',workspace.id),listEntities('uos_learning_skills',workspace.id),listEntities('uos_learning_study_sessions',workspace.id,'scheduled_at'),listEntities('uos_resources',workspace.id)])
      setCourses(projectId?c.filter(x=>x.project_id===projectId||!x.project_id):c)
      setModules(m)
      setLessons(projectId?l.filter(x=>x.project_id===projectId||!x.project_id):l)
      setSkills(projectId?s.filter(x=>x.project_id===projectId||!x.project_id):s)
      setSessions(projectId?ss.filter(x=>x.project_id===projectId||!x.project_id):ss)
      setResources(projectId?r.filter(x=>x.project_id===projectId||!x.project_id):r)
    }catch(e){setError(e.message)}
  }
  useEffect(()=>{load()},[workspace?.id,projectId])

  const courseName=id=>courses.find(c=>c.id===id)?.title||'—'
  const lessonName=id=>lessons.find(l=>l.id===id)?.title||'—'
  const skillName=id=>skills.find(s=>s.id===id)?.name||'—'
  const filteredModules=useMemo(()=>modules.filter(m=>!lesson.course_id||m.course_id===lesson.course_id),[modules,lesson.course_id])
  const filteredSessionLessons=useMemo(()=>lessons.filter(l=>!session.course_id||l.course_id===session.course_id),[lessons,session.course_id])

  const lessonProgress = lessonRow => lessonRow.duration_minutes ? Math.min(100,Math.round((Number(lessonRow.watched_minutes||0)/Number(lessonRow.duration_minutes))*100)) : 0
  const courseStats = useMemo(()=>courses.map(c=>{
    const rows=lessons.filter(l=>l.course_id===c.id)
    const duration=rows.reduce((sum,l)=>sum+Number(l.duration_minutes||0),0)
    const watched=rows.reduce((sum,l)=>sum+Math.min(Number(l.watched_minutes||0),Number(l.duration_minutes||0)),0)
    const remaining=Math.max(0,duration-watched)
    const progress=duration?Math.round(watched/duration*100):rows.length?Math.round(rows.filter(l=>l.status==='completed').length/rows.length*100):Number(c.progress||0)
    return {...c,lessonCount:rows.length,duration,watched,remaining,progress}
  }),[courses,lessons])
  const moduleStats = useMemo(()=>modules.map(m=>{
    const rows=lessons.filter(l=>l.module_id===m.id);const duration=rows.reduce((s,l)=>s+Number(l.duration_minutes||0),0);const watched=rows.reduce((s,l)=>s+Math.min(Number(l.watched_minutes||0),Number(l.duration_minutes||0)),0)
    return {...m,lessonCount:rows.length,remaining:Math.max(0,duration-watched),progress:duration?Math.round(watched/duration*100):rows.length?Math.round(rows.filter(l=>l.status==='completed').length/rows.length*100):0}
  }),[modules,lessons])

  async function addCourse(e){e.preventDefault();try{await createEntity('uos_learning_courses',{workspace_id:workspace.id,project_id:projectId||null,...course});setCourse({title:'',skill_id:'',description:'',status:'active'});load()}catch(e){setError(e.message)}}
  async function addModule(e){e.preventDefault();if(!module.course_id)return;try{await createEntity('uos_learning_modules',{workspace_id:workspace.id,...module,sort_order:Number(module.sort_order||0)});setModule({title:'',course_id:module.course_id,sort_order:'0'});load()}catch(e){setError(e.message)}}
  async function addLesson(e){e.preventDefault();if(!lesson.course_id)return;try{await createEntity('uos_learning_lessons',{workspace_id:workspace.id,...lesson,duration_minutes:lesson.duration_minutes?Number(lesson.duration_minutes):null,watched_minutes:lesson.watched_minutes?Number(lesson.watched_minutes):0,project_id:projectId||null});setLesson({title:'',course_id:lesson.course_id,module_id:'',duration_minutes:'',watched_minutes:'',skill_id:'',resource_id:'',status:'not_started'});load()}catch(e){setError(e.message)}}
  async function addSkill(e){e.preventDefault();if(!skill.name)return;try{await createEntity('uos_learning_skills',{workspace_id:workspace.id,project_id:projectId||null,...skill,target_level:skill.target_level?Number(skill.target_level):null,current_level:Number(skill.current_level||0)});setSkill({name:'',category:'',target_level:'',current_level:'0'});load()}catch(e){setError(e.message)}}
  async function addSession(e){e.preventDefault();try{await createEntity('uos_learning_study_sessions',{workspace_id:workspace.id,project_id:projectId||null,...session,duration_minutes:session.duration_minutes?Number(session.duration_minutes):null,actual_minutes:Number(session.actual_minutes||0)});setSession({course_id:'',lesson_id:'',skill_id:'',scheduled_at:'',duration_minutes:'',actual_minutes:'0',status:'planned',notes:''});load()}catch(e){setError(e.message)}}
  async function scheduleLesson(l){try{await createEntity('uos_learning_study_sessions',{workspace_id:workspace.id,project_id:projectId||null,course_id:l.course_id,lesson_id:l.id,skill_id:l.skill_id||null,scheduled_at:new Date(Date.now()+60*60*1000).toISOString(),duration_minutes:Math.max(15,Number(l.duration_minutes||30)-Number(l.watched_minutes||0)),actual_minutes:0,status:'planned',notes:`Study session for ${l.title}`});load()}catch(e){setError(e.message)}}
  async function remove(table,id){try{await deleteEntity(table,id);load()}catch(e){setError(e.message)}}

  const totalRemaining=courseStats.reduce((s,c)=>s+c.remaining,0)
  return <div><header className="page-head"><div><div className="eyebrow">LEARNING OS</div><h1>Learning + Skills</h1><p className="muted">Area → Course → Module → Lesson. التقدم والوقت المتبقي يتم استنتاجهما من دقائق المشاهدة الفعلية عندما تكون مدة الدرس متاحة.</p><div className="chip-row"><span className="chip selected">{projectId?'Project-scoped':'Workspace-wide'}</span><span className="chip">Time-weighted progress</span><span className="chip">Remaining: {formatMinutes(totalRemaining)}</span></div></div></header>{error&&<div className="error">{error}</div>}
    <div className="grid grid-4">{courseStats.slice(0,4).map(c=><div className="metric" key={c.id}><div className="muted">{c.title}</div><strong className="metric-value-wrap">{c.progress}%</strong><div className="progress-track"><span style={{width:`${c.progress}%`}}/></div><div className="muted">{formatMinutes(c.remaining)} remaining · {c.lessonCount} lessons</div></div>)}{!courseStats.length&&<div className="metric"><div className="muted">No courses</div><strong>0%</strong></div>}</div>
    <div className="grid grid-3 section">
      <div className="card"><h3>New Course</h3><form className="form-stack" onSubmit={addCourse}><input placeholder="اسم الدورة" value={course.title} onChange={e=>setCourse({...course,title:e.target.value})} required/><select value={course.skill_id} onChange={e=>setCourse({...course,skill_id:e.target.value})}><option value="">Skill اختياري</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><textarea rows="3" placeholder="وصف" value={course.description} onChange={e=>setCourse({...course,description:e.target.value})}/><button className="primary">إضافة Course</button></form></div>
      <div className="card"><h3>New Skill</h3><form className="form-stack" onSubmit={addSkill}><input placeholder="Skill" value={skill.name} onChange={e=>setSkill({...skill,name:e.target.value})} required/><input placeholder="Category" value={skill.category} onChange={e=>setSkill({...skill,category:e.target.value})}/><div className="form-grid"><input type="number" placeholder="Target level" value={skill.target_level} onChange={e=>setSkill({...skill,target_level:e.target.value})}/><input type="number" placeholder="Current level" value={skill.current_level} onChange={e=>setSkill({...skill,current_level:e.target.value})}/><button className="primary">إضافة Skill</button></div></form></div>
      <div className="card"><h3>New Study Session</h3><form className="form-stack" onSubmit={addSession}><select value={session.course_id} onChange={e=>setSession({...session,course_id:e.target.value,lesson_id:''})}><option value="">Course اختياري</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><select value={session.lesson_id} onChange={e=>setSession({...session,lesson_id:e.target.value})}><option value="">Lesson اختياري</option>{filteredSessionLessons.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select><select value={session.skill_id} onChange={e=>setSession({...session,skill_id:e.target.value})}><option value="">Skill اختياري</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="form-grid"><input type="datetime-local" value={session.scheduled_at} onChange={e=>setSession({...session,scheduled_at:e.target.value})}/><input type="number" placeholder="Planned minutes" value={session.duration_minutes} onChange={e=>setSession({...session,duration_minutes:e.target.value})}/><select value={session.status} onChange={e=>setSession({...session,status:e.target.value})}>{SESSION_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div><textarea rows="2" placeholder="Notes" value={session.notes} onChange={e=>setSession({...session,notes:e.target.value})}/><button className="primary">إضافة Session</button></form></div>
    </div>

    <section className="section grid grid-2"><div className="card"><div className="section-head"><h3>Courses</h3><span className="muted">{courses.length}</span></div>{courseStats.map(c=><div className="list-row" key={c.id}><div className="between"><strong>{c.title}</strong><span className="badge info">{c.progress}%</span></div><div className="progress-track"><span style={{width:`${c.progress}%`}}/></div><div className="muted">{c.watched} / {c.duration || 0} min watched · {formatMinutes(c.remaining)} remaining · {c.lessonCount} lessons</div></div>)}{!courses.length&&<div className="muted">لا توجد دورات.</div>}</div><div className="card"><div className="section-head"><h3>Module / Chapter Progress</h3><span className="muted">{modules.length}</span></div>{moduleStats.map(m=><div className="list-row" key={m.id}><div className="between"><strong>{m.title}</strong><span className="badge info">{m.progress}%</span></div><div className="progress-track"><span style={{width:`${m.progress}%`}}/></div><div className="muted">{m.lessonCount} lessons · {formatMinutes(m.remaining)} remaining</div></div>)}{!modules.length&&<div className="muted">لا توجد Modules.</div>}</div></section>

    <section className="section grid grid-2"><div className="card"><h3>Lessons</h3>{lessons.map(l=>{const pct=lessonProgress(l), remaining=Math.max(0,Number(l.duration_minutes||0)-Number(l.watched_minutes||0));return <div className="list-row" key={l.id}><div className="between"><strong>{l.title}</strong><span className="badge info">{pct}%</span></div><div className="progress-track"><span style={{width:`${pct}%`}}/></div><div className="muted">{courseName(l.course_id)} · {skillName(l.skill_id)} · {formatMinutes(remaining)} remaining {l.resource_id?'· Resource linked':''}</div><div className="actions"><button className="secondary" onClick={()=>scheduleLesson(l)}>Schedule Study Session</button><button className="danger" onClick={()=>remove('uos_learning_lessons',l.id)}>حذف</button></div></div>})}{!lessons.length&&<div className="muted">لا توجد دروس.</div>}</div><div className="card"><h3>Study Sessions</h3>{sessions.map(s=><div className="list-row between" key={s.id}><div><strong>{lessonName(s.lesson_id)}</strong><div className="muted">{courseName(s.course_id)} · {skillName(s.skill_id)} · {s.status} · {s.scheduled_at?new Date(s.scheduled_at).toLocaleString('ar-EG'):''}</div></div><button className="danger" onClick={()=>remove('uos_learning_study_sessions',s.id)}>حذف</button></div>)}{!sessions.length&&<div className="muted">لا توجد Study Sessions.</div>}</div></section>

    <section className="section card"><div className="section-head"><div><div className="eyebrow">MODULE / LESSON</div><h3>Learning structure</h3></div></div><div className="grid grid-2"><form className="form-stack" onSubmit={addModule}><input placeholder="اسم الـModule / Chapter" value={module.title} onChange={e=>setModule({...module,title:e.target.value})} required/><select value={module.course_id} onChange={e=>setModule({...module,course_id:e.target.value})}><option value="">اختر Course</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><input type="number" placeholder="Order" value={module.sort_order} onChange={e=>setModule({...module,sort_order:e.target.value})}/><button className="primary">إضافة Module</button></form><form className="form-stack" onSubmit={addLesson}><input placeholder="عنوان الدرس" value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})} required/><select value={lesson.course_id} onChange={e=>setLesson({...lesson,course_id:e.target.value})}><option value="">اختر Course</option>{courses.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select><select value={lesson.module_id} onChange={e=>setLesson({...lesson,module_id:e.target.value})}><option value="">بدون Module</option>{filteredModules.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select><select value={lesson.skill_id} onChange={e=>setLesson({...lesson,skill_id:e.target.value})}><option value="">Skill اختياري</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={lesson.resource_id} onChange={e=>setLesson({...lesson,resource_id:e.target.value})}><option value="">Resource اختياري</option>{resources.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select><div className="form-grid"><input type="number" placeholder="Duration" value={lesson.duration_minutes} onChange={e=>setLesson({...lesson,duration_minutes:e.target.value})}/><input type="number" placeholder="Watched" value={lesson.watched_minutes} onChange={e=>setLesson({...lesson,watched_minutes:e.target.value})}/><select value={lesson.status} onChange={e=>setLesson({...lesson,status:e.target.value})}><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></div><button className="primary">إضافة Lesson</button></form></div></section>
  </div>
}
function formatMinutes(value){const n=Number(value||0);if(!n)return '0 min';const h=Math.floor(n/60),m=n%60;return h?`${h}h ${m}m`: `${m}m`}
