-- Phase 18 — Security + Permissions + Audit
-- Backend authorization is authoritative. UI guards are convenience only.
create extension if not exists pgcrypto;

create table if not exists uos_workspace_members (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references uos_workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin','manager','editor','contributor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, user_id)
);

create table if not exists uos_project_members (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references uos_workspaces(id) on delete cascade,
  project_id uuid not null references uos_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin','manager','editor','contributor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, user_id)
);

create table if not exists uos_finance_permissions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references uos_workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  can_view boolean not null default true,
  can_edit boolean not null default false,
  can_export boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, user_id)
);

create table if not exists uos_content_account_permissions (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references uos_workspaces(id) on delete cascade,
  project_id uuid not null references uos_projects(id) on delete cascade,
  content_account_id text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin','manager','editor','contributor','viewer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(project_id, content_account_id, user_id)
);

create table if not exists uos_audit_log (
  id bigint generated by default as identity primary key,
  workspace_id uuid references uos_workspaces(id) on delete set null,
  project_id uuid references uos_projects(id) on delete set null,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_table text not null,
  entity_id text,
  old_values jsonb,
  new_values jsonb,
  reason text,
  source text not null default 'database_trigger',
  created_at timestamptz not null default now()
);

create index if not exists idx_uos_workspace_members_ws on uos_workspace_members(workspace_id, active, role);
create index if not exists idx_uos_workspace_members_user on uos_workspace_members(user_id, active);
create index if not exists idx_uos_project_members_project on uos_project_members(project_id, active, role);
create index if not exists idx_uos_project_members_user on uos_project_members(user_id, active);
create index if not exists idx_uos_finance_permissions_ws on uos_finance_permissions(workspace_id, user_id);
create index if not exists idx_uos_content_account_permissions_project on uos_content_account_permissions(project_id, content_account_id, active);
create index if not exists idx_uos_audit_log_ws_created on uos_audit_log(workspace_id, created_at desc);
create index if not exists idx_uos_audit_log_project_created on uos_audit_log(project_id, created_at desc);
create index if not exists idx_uos_audit_log_actor_created on uos_audit_log(actor_id, created_at desc);

create or replace function uos_role_rank(p_role text)
returns int language sql immutable as $$
  select case lower(coalesce(p_role,''))
    when 'viewer' then 10
    when 'contributor' then 20
    when 'editor' then 30
    when 'manager' then 40
    when 'admin' then 50
    when 'owner' then 60
    else 0
  end
$$;

create or replace function uos_workspace_role(p_workspace uuid, p_user uuid default auth.uid())
returns text language sql stable security definer set search_path=public as $$
  select case
    when w.owner_id = p_user then 'owner'
    else coalesce(max(m.role) filter (where m.active), 'none')
  end
  from uos_workspaces w
  left join uos_workspace_members m on m.workspace_id = w.id and m.user_id = p_user
  where w.id = p_workspace
  group by w.id, w.owner_id
$$;

create or replace function uos_is_member(p_workspace uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_workspace_role(p_workspace, auth.uid()) <> 'none'
$$;

create or replace function uos_can_read_workspace(p_workspace uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, auth.uid())) >= 10
$$;

create or replace function uos_can_write_workspace(p_workspace uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, auth.uid())) >= 20
$$;

create or replace function uos_can_delete_workspace(p_workspace uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, auth.uid())) >= 30
$$;

create or replace function uos_can_manage_workspace(p_workspace uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, auth.uid())) >= 50
$$;

create or replace function uos_project_role(p_project uuid, p_user uuid default auth.uid())
returns text language sql stable security definer set search_path=public as $$
  with p as (select id, workspace_id, owner_id from uos_projects where id = p_project),
  explicit as (
    select pm.role from uos_project_members pm where pm.project_id = p_project and pm.user_id = p_user and pm.active limit 1
  )
  select case
    when p.owner_id = p_user then 'owner'
    when uos_role_rank(uos_workspace_role(p.workspace_id, p_user)) >= 50 then uos_workspace_role(p.workspace_id, p_user)
    when exists(select 1 from uos_project_members pm where pm.project_id = p_project and pm.active) then coalesce((select role from explicit), 'none')
    else uos_workspace_role(p.workspace_id, p_user)
  end
  from p
$$;

create or replace function uos_can_read_project(p_project uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_project_role(p_project, auth.uid())) >= 10
$$;

create or replace function uos_can_write_project(p_project uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_project_role(p_project, auth.uid())) >= 20
$$;

create or replace function uos_can_delete_project(p_project uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_project_role(p_project, auth.uid())) >= 30
$$;

create or replace function uos_can_manage_project(p_project uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_project_role(p_project, auth.uid())) >= 40
$$;

create or replace function uos_can_read_content_account(p_project uuid, p_account text)
returns boolean language sql stable security definer set search_path=public as $$
  select case
    when uos_can_manage_project(p_project) then true
    when not exists(select 1 from uos_content_account_permissions cap where cap.project_id=p_project and cap.content_account_id=p_account and cap.active)
      and not exists(select 1 from uos_content_account_permissions cap where cap.project_id=p_project and cap.content_account_id=p_account)
      then uos_can_read_project(p_project)
    else exists(select 1 from uos_content_account_permissions cap where cap.project_id=p_project and cap.content_account_id=p_account and cap.user_id=auth.uid() and cap.active and uos_role_rank(cap.role) >= 10)
  end
$$;

create or replace function uos_can_write_content_account(p_project uuid, p_account text)
returns boolean language sql stable security definer set search_path=public as $$
  select case
    when uos_can_manage_project(p_project) then true
    when not exists(select 1 from uos_content_account_permissions cap where cap.project_id=p_project and cap.content_account_id=p_account)
      then uos_can_write_project(p_project)
    else exists(select 1 from uos_content_account_permissions cap where cap.project_id=p_project and cap.content_account_id=p_account and cap.user_id=auth.uid() and cap.active and uos_role_rank(cap.role) >= 20)
  end
$$;

create or replace function uos_can_view_finance(p_workspace uuid, p_user uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, p_user)) >= 40
      or exists(select 1 from uos_finance_permissions fp where fp.workspace_id=p_workspace and fp.user_id=p_user and fp.can_view)
$$;

create or replace function uos_can_edit_finance(p_workspace uuid, p_user uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, p_user)) >= 40
      or exists(select 1 from uos_finance_permissions fp where fp.workspace_id=p_workspace and fp.user_id=p_user and fp.can_edit)
$$;

create or replace function uos_can_export_finance(p_workspace uuid, p_user uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, p_user)) >= 40
      or exists(select 1 from uos_finance_permissions fp where fp.workspace_id=p_workspace and fp.user_id=p_user and fp.can_export)
$$;

create or replace function uos_can_manage_audit(p_workspace uuid, p_user uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select uos_role_rank(uos_workspace_role(p_workspace, p_user)) >= 40
$$;

create or replace function uos_authorize_action(
  p_workspace uuid,
  p_project uuid,
  p_resource text,
  p_action text
) returns boolean language plpgsql stable security definer set search_path=public as $$
begin
  case lower(coalesce(p_resource,''))
    when 'finance' then
      return case lower(coalesce(p_action,''))
        when 'read' then uos_can_view_finance(p_workspace)
        when 'create', 'update' then uos_can_edit_finance(p_workspace)
        when 'delete', 'manage' then uos_role_rank(uos_workspace_role(p_workspace)) >= 50
        when 'export' then uos_can_export_finance(p_workspace)
        else false end;
    when 'project' then
      return case lower(coalesce(p_action,''))
        when 'read' then uos_can_read_project(p_project)
        when 'create', 'update' then uos_can_write_project(p_project)
        when 'delete' then uos_can_delete_project(p_project)
        when 'manage' then uos_can_manage_project(p_project)
        else false end;
    when 'workspace' then
      return case lower(coalesce(p_action,''))
        when 'read' then uos_can_read_workspace(p_workspace)
        when 'create', 'update' then uos_can_write_workspace(p_workspace)
        when 'delete' then uos_role_rank(uos_workspace_role(p_workspace)) >= 60
        when 'manage' then uos_can_manage_workspace(p_workspace)
        else false end;
    when 'audit' then
      return case lower(coalesce(p_action,'')) when 'read', 'export' then uos_can_manage_audit(p_workspace) else false end;
    else
      return case lower(coalesce(p_action,''))
        when 'read' then uos_can_read_workspace(p_workspace)
        when 'create', 'update' then uos_can_write_workspace(p_workspace)
        when 'delete' then uos_can_delete_workspace(p_workspace)
        when 'manage' then uos_can_manage_workspace(p_workspace)
        else false end;
  end case;
end
$$;

-- Seed owner memberships for all existing workspaces and project owners.
insert into uos_workspace_members(workspace_id,user_id,role,active)
select w.id,w.owner_id,'admin',true from uos_workspaces w
on conflict (workspace_id,user_id) do update set active=true, updated_at=now();

insert into uos_project_members(workspace_id,project_id,user_id,role,active)
select p.workspace_id,p.id,p.owner_id,'admin',true from uos_projects p where p.owner_id is not null
on conflict (project_id,user_id) do update set active=true, updated_at=now();

create or replace function uos_seed_owner_membership() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into uos_workspace_members(workspace_id,user_id,role,active)
  values(new.id,new.owner_id,'admin',true)
  on conflict (workspace_id,user_id) do update set active=true, updated_at=now();
  return new;
end $$;

drop trigger if exists trg_uos_seed_workspace_owner on uos_workspaces;
create trigger trg_uos_seed_workspace_owner after insert on uos_workspaces
for each row execute function uos_seed_owner_membership();

create or replace function uos_seed_project_owner_membership() returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.owner_id is not null then
    insert into uos_project_members(workspace_id,project_id,user_id,role,active)
    values(new.workspace_id,new.id,new.owner_id,'admin',true)
    on conflict (project_id,user_id) do update set active=true, updated_at=now();
  end if;
  return new;
end $$;

drop trigger if exists trg_uos_seed_project_owner on uos_projects;
create trigger trg_uos_seed_project_owner after insert on uos_projects
for each row execute function uos_seed_project_owner_membership();

-- Replace the old owner-only membership function semantics with role-aware membership.
-- Rebuild RLS policies for all current workspace-scoped tables.
do $$
declare
  r record;
  has_project boolean;
  stmt text;
  tbl text;
  excluded constant text[] := array['uos_workspace_members','uos_project_members','uos_finance_permissions','uos_content_account_permissions','uos_audit_log','uos_workspaces','uos_fin_accounts','uos_fin_categories','uos_fin_transactions','uos_fin_budgets','uos_fin_recurring','uos_fin_debts','uos_fin_savings_goals'];
begin
  for r in select distinct c.table_name
           from information_schema.columns c
           join information_schema.tables t on t.table_schema=c.table_schema and t.table_name=c.table_name
          where c.table_schema='public' and c.column_name='workspace_id' and c.table_name like 'uos_%' and t.table_type='BASE TABLE'
  loop
    tbl := r.table_name;
    if tbl = any(excluded) then continue; end if;
    has_project := exists(select 1 from information_schema.columns where table_schema='public' and table_name=tbl and column_name='project_id');
    execute format('drop policy if exists %I_read on %I',tbl,tbl);
    execute format('drop policy if exists %I_insert on %I',tbl,tbl);
    execute format('drop policy if exists %I_update on %I',tbl,tbl);
    execute format('drop policy if exists %I_delete on %I',tbl,tbl);
    if tbl='uos_projects' then
      execute format('create policy %I_read on %I for select to authenticated using (uos_can_read_project(id))',tbl,tbl);
      execute format('create policy %I_insert on %I for insert to authenticated with check (uos_can_write_workspace(workspace_id))',tbl,tbl);
      execute format('create policy %I_update on %I for update to authenticated using (uos_can_write_project(id)) with check (uos_can_write_project(id))',tbl,tbl);
      execute format('create policy %I_delete on %I for delete to authenticated using (uos_can_delete_project(id))',tbl,tbl);
    elsif has_project then
      execute format('create policy %I_read on %I for select to authenticated using (project_id is null or uos_can_read_project(project_id))',tbl,tbl);
      execute format('create policy %I_insert on %I for insert to authenticated with check (project_id is null or uos_can_write_project(project_id))',tbl,tbl);
      execute format('create policy %I_update on %I for update to authenticated using (project_id is null or uos_can_write_project(project_id)) with check (project_id is null or uos_can_write_project(project_id))',tbl,tbl);
      execute format('create policy %I_delete on %I for delete to authenticated using (project_id is null or uos_can_delete_project(project_id))',tbl,tbl);
    else
      execute format('create policy %I_read on %I for select to authenticated using (uos_can_read_workspace(workspace_id))',tbl,tbl);
      execute format('create policy %I_insert on %I for insert to authenticated with check (uos_can_write_workspace(workspace_id))',tbl,tbl);
      execute format('create policy %I_update on %I for update to authenticated using (uos_can_write_workspace(workspace_id)) with check (uos_can_write_workspace(workspace_id))',tbl,tbl);
      execute format('create policy %I_delete on %I for delete to authenticated using (uos_can_delete_workspace(workspace_id))',tbl,tbl);
    end if;
  end loop;
end $$;

-- Projects get stricter project-aware permissions, while catalog tables stay read-only.
alter table if exists uos_project_profiles enable row level security;
alter table if exists uos_project_module_catalog enable row level security;
drop policy if exists uos_project_profiles_read on uos_project_profiles;
create policy uos_project_profiles_read on uos_project_profiles for select to authenticated using (active);
drop policy if exists uos_project_module_catalog_read on uos_project_module_catalog;
create policy uos_project_module_catalog_read on uos_project_module_catalog for select to authenticated using (active);

-- Workspaces are the root security boundary.
alter table uos_workspaces enable row level security;
drop policy if exists uos_workspaces_owner on uos_workspaces;
drop policy if exists uos_workspaces_read on uos_workspaces;
drop policy if exists uos_workspaces_update on uos_workspaces;
drop policy if exists uos_workspaces_insert on uos_workspaces;
drop policy if exists uos_workspaces_delete on uos_workspaces;
create policy uos_workspaces_read on uos_workspaces for select to authenticated using (uos_can_read_workspace(id));
create policy uos_workspaces_insert on uos_workspaces for insert to authenticated with check (owner_id=auth.uid());
create policy uos_workspaces_update on uos_workspaces for update to authenticated using (uos_role_rank(uos_workspace_role(id)) >= 50) with check (uos_role_rank(uos_workspace_role(id)) >= 50);
create policy uos_workspaces_delete on uos_workspaces for delete to authenticated using (uos_role_rank(uos_workspace_role(id)) >= 60);

-- Sensitive Finance tables: view requires Finance visibility, edits require Finance edit permission, deletes require admin/owner.
do $$ declare t text; begin foreach t in array array['uos_fin_accounts','uos_fin_categories','uos_fin_transactions','uos_fin_budgets','uos_fin_recurring','uos_fin_debts','uos_fin_savings_goals'] loop
  execute format('drop policy if exists %I_owner_all on %I',t,t);
  execute format('drop policy if exists %I_read on %I',t,t);
  execute format('drop policy if exists %I_write on %I',t,t);
  execute format('drop policy if exists %I_delete on %I',t,t);
  execute format('create policy %I_read on %I for select to authenticated using (uos_can_view_finance(workspace_id))',t,t);
  execute format('create policy %I_write on %I for insert to authenticated with check (uos_can_edit_finance(workspace_id))',t,t);
  execute format('create policy %I_update on %I for update to authenticated using (uos_can_edit_finance(workspace_id)) with check (uos_can_edit_finance(workspace_id))',t,t);
  execute format('create policy %I_delete on %I for delete to authenticated using (uos_role_rank(uos_workspace_role(workspace_id)) >= 50)',t,t);
end loop; end $$;

-- Security metadata policies.
alter table uos_workspace_members enable row level security;
drop policy if exists uos_workspace_members_read on uos_workspace_members;
drop policy if exists uos_workspace_members_write on uos_workspace_members;
create policy uos_workspace_members_read on uos_workspace_members for select to authenticated
using (user_id=auth.uid() or uos_can_manage_workspace(workspace_id));
create policy uos_workspace_members_write on uos_workspace_members for all to authenticated
using (uos_can_manage_workspace(workspace_id)) with check (uos_can_manage_workspace(workspace_id));

alter table uos_project_members enable row level security;
drop policy if exists uos_project_members_read on uos_project_members;
drop policy if exists uos_project_members_write on uos_project_members;
create policy uos_project_members_read on uos_project_members for select to authenticated
using (user_id=auth.uid() or uos_can_manage_project(project_id));
create policy uos_project_members_write on uos_project_members for all to authenticated
using (uos_can_manage_project(project_id)) with check (uos_can_manage_project(project_id));

alter table uos_finance_permissions enable row level security;
drop policy if exists uos_finance_permissions_read on uos_finance_permissions;
drop policy if exists uos_finance_permissions_write on uos_finance_permissions;
create policy uos_finance_permissions_read on uos_finance_permissions for select to authenticated
using (user_id=auth.uid() or uos_can_manage_workspace(workspace_id));
create policy uos_finance_permissions_write on uos_finance_permissions for all to authenticated
using (uos_can_manage_workspace(workspace_id)) with check (uos_can_manage_workspace(workspace_id));

alter table uos_content_account_permissions enable row level security;
drop policy if exists uos_content_account_permissions_read on uos_content_account_permissions;
drop policy if exists uos_content_account_permissions_write on uos_content_account_permissions;
create policy uos_content_account_permissions_read on uos_content_account_permissions for select to authenticated
using (user_id=auth.uid() or uos_can_manage_project(project_id));
create policy uos_content_account_permissions_write on uos_content_account_permissions for all to authenticated
using (uos_can_manage_project(project_id)) with check (uos_can_manage_project(project_id));


-- Existing ContentOS account links remain governed by project permissions plus optional per-account overlays.
alter table uos_project_content_accounts enable row level security;
drop policy if exists uos_project_content_accounts_read on uos_project_content_accounts;
drop policy if exists uos_project_content_accounts_insert on uos_project_content_accounts;
drop policy if exists uos_project_content_accounts_update on uos_project_content_accounts;
drop policy if exists uos_project_content_accounts_delete on uos_project_content_accounts;
create policy uos_project_content_accounts_read on uos_project_content_accounts for select to authenticated
using (uos_can_read_content_account(project_id, content_account_id));
create policy uos_project_content_accounts_insert on uos_project_content_accounts for insert to authenticated
with check (uos_can_write_content_account(project_id, content_account_id));
create policy uos_project_content_accounts_update on uos_project_content_accounts for update to authenticated
using (uos_can_write_content_account(project_id, content_account_id))
with check (uos_can_write_content_account(project_id, content_account_id));
create policy uos_project_content_accounts_delete on uos_project_content_accounts for delete to authenticated
using (uos_can_delete_project(project_id));

alter table uos_audit_log enable row level security;
drop policy if exists uos_audit_log_read on uos_audit_log;
drop policy if exists uos_audit_log_write on uos_audit_log;
create policy uos_audit_log_read on uos_audit_log for select to authenticated using (uos_can_manage_audit(workspace_id));

-- Database-level audit trail. Client roles cannot directly write to the audit table.
create or replace function uos_audit_row_change() returns trigger language plpgsql security definer set search_path=public as $$
declare
  row_json jsonb;
  old_json jsonb;
  new_json jsonb;
  ws uuid;
  proj uuid;
  entity_id text;
  actor uuid;
begin
  old_json := case when TG_OP in ('UPDATE','DELETE') then to_jsonb(OLD) else null end;
  new_json := case when TG_OP in ('INSERT','UPDATE') then to_jsonb(NEW) else null end;
  row_json := coalesce(new_json, old_json, '{}'::jsonb);
  ws := nullif(row_json->>'workspace_id','')::uuid;
  proj := nullif(row_json->>'project_id','')::uuid;
  entity_id := coalesce(row_json->>'id', '');
  actor := auth.uid();
  insert into uos_audit_log(workspace_id,project_id,actor_id,action,entity_table,entity_id,old_values,new_values,reason,source)
  values(ws,proj,actor,TG_OP,TG_TABLE_NAME,entity_id,old_json,new_json,current_setting('uos.audit.reason',true),'database_trigger');
  return coalesce(NEW, OLD);
end $$;

create or replace function uos_audit_workspace_change() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into uos_audit_log(workspace_id,actor_id,action,entity_table,entity_id,old_values,new_values,reason,source)
  values(coalesce(NEW.id,OLD.id),auth.uid(),TG_OP,TG_TABLE_NAME,(coalesce(NEW.id,OLD.id))::text,
         case when TG_OP in ('UPDATE','DELETE') then to_jsonb(OLD) else null end,
         case when TG_OP in ('INSERT','UPDATE') then to_jsonb(NEW) else null end,
         current_setting('uos.audit.reason',true),'database_trigger');
  return coalesce(NEW,OLD);
end $$;

drop trigger if exists trg_uos_audit_workspaces on uos_workspaces;
create trigger trg_uos_audit_workspaces after insert or update or delete on uos_workspaces
for each row execute function uos_audit_workspace_change();

do $$
declare r record;
begin
  for r in select distinct c.table_name
           from information_schema.columns c
           join information_schema.tables t on t.table_schema=c.table_schema and t.table_name=c.table_name
          where c.table_schema='public' and c.column_name='workspace_id' and c.table_name like 'uos_%'
            and t.table_type='BASE TABLE'
            and c.table_name not in ('uos_audit_log')
  loop
    execute format('drop trigger if exists %I on %I', 'trg_uos_audit_'||r.table_name, r.table_name);
    execute format('create trigger %I after insert or update or delete on %I for each row execute function uos_audit_row_change()', 'trg_uos_audit_'||r.table_name, r.table_name);
  end loop;
end $$;

-- Documentation/observability metadata for the application layer.
create or replace function uos_security_context(p_workspace uuid)
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'workspaceId', p_workspace,
    'role', uos_workspace_role(p_workspace, auth.uid()),
    'canRead', uos_can_read_workspace(p_workspace),
    'canWrite', uos_can_write_workspace(p_workspace),
    'canDelete', uos_can_delete_workspace(p_workspace),
    'canManage', uos_can_manage_workspace(p_workspace),
    'canViewFinance', uos_can_view_finance(p_workspace, auth.uid()),
    'canEditFinance', uos_can_edit_finance(p_workspace, auth.uid()),
    'canExportFinance', uos_can_export_finance(p_workspace, auth.uid()),
    'canViewAudit', uos_can_manage_audit(p_workspace, auth.uid())
  )
$$;

-- Security hardening markers.
comment on table uos_workspace_members is 'Workspace membership and role assignments. Owner is derived from uos_workspaces.owner_id.';
comment on table uos_project_members is 'Optional project-level membership override. If no explicit members exist, workspace membership applies.';
comment on table uos_finance_permissions is 'Explicit Finance visibility/edit/export overrides. Manager/Admin/Owner remain privileged by role.';
comment on table uos_content_account_permissions is 'Unified OS access overlay for existing ContentOS accounts. Does not replace ContentOS-native permissions.';
comment on table uos_audit_log is 'Authoritative database audit trail for Unified OS changes. Client roles are read-only.';
