-- Phase 19 — Versioning + Migration + Backup + Restore + Rollback
-- Unified OS recovery control plane. Existing ContentOS recovery remains authoritative and is not duplicated here.
create extension if not exists pgcrypto;

create table if not exists uos_schema_registry (
  id boolean primary key default true check (id),
  current_version text not null,
  minimum_compatible_version text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists uos_migration_log (
  id uuid primary key default gen_random_uuid(),
  version text not null unique,
  migration_name text not null,
  checksum text not null,
  status text not null default 'applied' check (status in ('pending','applied','failed','rolled_back')),
  applied_at timestamptz not null default now(),
  applied_by uuid references auth.users(id) on delete set null,
  notes text
);

create table if not exists uos_recovery_snapshots (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references uos_workspaces(id) on delete cascade,
  snapshot_type text not null default 'manual' check (snapshot_type in ('protective','manual','pre_migration','export')),
  schema_version text not null,
  created_by uuid references auth.users(id) on delete set null,
  status text not null default 'ready' check (status in ('creating','ready','failed','restored','rolled_back')),
  table_count integer not null default 0,
  row_count bigint not null default 0,
  manifest jsonb not null default '{}'::jsonb,
  checksum text,
  restored_to_workspace_id uuid references uos_workspaces(id) on delete set null,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  notes text
);

create table if not exists uos_recovery_items (
  id bigint generated by default as identity primary key,
  snapshot_id uuid not null references uos_recovery_snapshots(id) on delete cascade,
  table_name text not null,
  row_count bigint not null default 0,
  payload jsonb not null default '[]'::jsonb,
  checksum text not null,
  unique(snapshot_id, table_name)
);

create table if not exists uos_recovery_runs (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid references uos_workspaces(id) on delete set null,
  snapshot_id uuid references uos_recovery_snapshots(id) on delete set null,
  restored_to_workspace_id uuid references uos_workspaces(id) on delete set null,
  action text not null check (action in ('snapshot','export','restore','rollback','compatibility_check')),
  status text not null default 'started' check (status in ('started','success','failed')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  actor_id uuid references auth.users(id) on delete set null,
  summary jsonb not null default '{}'::jsonb,
  error text
);

create index if not exists idx_uos_migration_log_applied on uos_migration_log(applied_at desc);
create index if not exists idx_uos_recovery_snapshots_ws on uos_recovery_snapshots(workspace_id, created_at desc);
create index if not exists idx_uos_recovery_items_snapshot on uos_recovery_items(snapshot_id);
create index if not exists idx_uos_recovery_runs_ws on uos_recovery_runs(workspace_id, started_at desc);

insert into uos_schema_registry(id,current_version,minimum_compatible_version,updated_by)
values(true,'022','010',auth.uid())
on conflict (id) do update set current_version=excluded.current_version, minimum_compatible_version=excluded.minimum_compatible_version, updated_at=now(), updated_by=auth.uid();

insert into uos_migration_log(version,migration_name,checksum,status,applied_by,notes)
values('022','versioning-recovery','phase19-control-plane','applied',auth.uid(),'Unified OS recovery metadata. ContentOS recovery remains external/authoritative.')
on conflict (version) do update set status='applied', checksum=excluded.checksum, applied_at=now(), applied_by=auth.uid(), notes=excluded.notes;

alter table uos_schema_registry enable row level security;
alter table uos_migration_log enable row level security;
alter table uos_recovery_snapshots enable row level security;
alter table uos_recovery_items enable row level security;
alter table uos_recovery_runs enable row level security;

drop policy if exists uos_schema_registry_read on uos_schema_registry;
create policy uos_schema_registry_read on uos_schema_registry for select to authenticated using (true);
drop policy if exists uos_migration_log_read on uos_migration_log;
create policy uos_migration_log_read on uos_migration_log for select to authenticated using (true);

drop policy if exists uos_recovery_snapshots_read on uos_recovery_snapshots;
create policy uos_recovery_snapshots_read on uos_recovery_snapshots for select to authenticated using (uos_can_read_workspace(workspace_id));
drop policy if exists uos_recovery_snapshots_manage on uos_recovery_snapshots;
create policy uos_recovery_snapshots_manage on uos_recovery_snapshots for all to authenticated using (uos_can_manage_workspace(workspace_id)) with check (uos_can_manage_workspace(workspace_id));

drop policy if exists uos_recovery_items_read on uos_recovery_items;
create policy uos_recovery_items_read on uos_recovery_items for select to authenticated using (exists(select 1 from uos_recovery_snapshots s where s.id=snapshot_id and uos_can_read_workspace(s.workspace_id)));
drop policy if exists uos_recovery_items_manage on uos_recovery_items;
create policy uos_recovery_items_manage on uos_recovery_items for all to authenticated using (exists(select 1 from uos_recovery_snapshots s where s.id=snapshot_id and uos_can_manage_workspace(s.workspace_id))) with check (exists(select 1 from uos_recovery_snapshots s where s.id=snapshot_id and uos_can_manage_workspace(s.workspace_id)));

drop policy if exists uos_recovery_runs_read on uos_recovery_runs;
create policy uos_recovery_runs_read on uos_recovery_runs for select to authenticated using (workspace_id is null or uos_can_read_workspace(workspace_id));
drop policy if exists uos_recovery_runs_manage on uos_recovery_runs;
create policy uos_recovery_runs_manage on uos_recovery_runs for insert to authenticated with check (workspace_id is null or uos_can_manage_workspace(workspace_id));

create or replace function uos_recovery_excluded_table(p_table text)
returns boolean language sql immutable as $$
  select p_table = any(array[
    'uos_workspaces',
    'uos_schema_registry',
    'uos_migration_log',
    'uos_recovery_snapshots',
    'uos_recovery_items',
    'uos_recovery_runs',
    'uos_audit_log'
  ])
$$;

create or replace function uos_create_recovery_snapshot(
  p_workspace uuid,
  p_snapshot_type text default 'manual'
) returns uuid
language plpgsql security definer set search_path=public as $$
declare
  v_snapshot uuid;
  v_run uuid;
  r record;
  v_payload jsonb;
  v_rows bigint;
  v_table_count integer := 0;
  v_total_rows bigint := 0;
  v_manifest jsonb := '[]'::jsonb;
begin
  if not uos_can_manage_workspace(p_workspace) then
    raise exception 'recovery snapshot requires workspace manager/admin access';
  end if;

  insert into uos_recovery_snapshots(workspace_id,snapshot_type,schema_version,created_by,status)
  values(p_workspace,p_snapshot_type,'022',auth.uid(),'creating')
  returning id into v_snapshot;

  insert into uos_recovery_runs(workspace_id,snapshot_id,action,actor_id)
  values(p_workspace,v_snapshot,'snapshot',auth.uid())
  returning id into v_run;

  for r in
    select c.table_name
      from information_schema.columns c
      join information_schema.tables t on t.table_schema=c.table_schema and t.table_name=c.table_name
     where c.table_schema='public'
       and c.column_name='workspace_id'
       and c.table_name like 'uos_%'
       and t.table_type='BASE TABLE'
       and not uos_recovery_excluded_table(c.table_name)
     group by c.table_name
     order by c.table_name
  loop
    execute format('select coalesce(jsonb_agg(to_jsonb(x)), ''[]''::jsonb) from (select * from %I where workspace_id = $1) x', r.table_name)
      into v_payload using p_workspace;
    v_rows := jsonb_array_length(v_payload);
    insert into uos_recovery_items(snapshot_id,table_name,row_count,payload,checksum)
    values(v_snapshot,r.table_name,v_rows,v_payload,encode(digest(v_payload::text,'sha256'),'hex'));
    v_table_count := v_table_count + 1;
    v_total_rows := v_total_rows + v_rows;
    v_manifest := v_manifest || jsonb_build_array(jsonb_build_object('table',r.table_name,'rows',v_rows));
  end loop;

  update uos_recovery_snapshots
     set status='ready', table_count=v_table_count, row_count=v_total_rows,
         manifest=jsonb_build_object('schemaVersion','022','workspaceId',p_workspace,'tables',v_manifest),
         checksum=encode(digest(v_manifest::text,'sha256'),'hex'), completed_at=now()
   where id=v_snapshot;

  update uos_recovery_runs set status='success', completed_at=now(), summary=jsonb_build_object('tables',v_table_count,'rows',v_total_rows) where id=v_run;
  return v_snapshot;
exception when others then
  if v_snapshot is not null then
    update uos_recovery_snapshots set status='failed', completed_at=now(), notes=sqlerrm where id=v_snapshot;
  end if;
  if v_run is not null then
    update uos_recovery_runs set status='failed', completed_at=now(), error=sqlerrm where id=v_run;
  end if;
  raise;
end
$$;

create or replace function uos_validate_recovery_snapshot(p_snapshot uuid)
returns jsonb
language plpgsql security definer set search_path=public as $$
declare
  v_schema text;
  v_tables integer;
  v_rows bigint;
  v_bad_checksums integer := 0;
  v_missing_tables text[] := '{}';
  r record;
begin
  select schema_version,table_count,row_count into v_schema,v_tables,v_rows from uos_recovery_snapshots where id=p_snapshot;
  if v_schema is null then raise exception 'snapshot not found'; end if;
  for r in select table_name,checksum,payload from uos_recovery_items where snapshot_id=p_snapshot loop
    if encode(digest(r.payload::text,'sha256'),'hex') <> r.checksum then
      v_bad_checksums := v_bad_checksums + 1;
    end if;
    if not exists(select 1 from information_schema.tables where table_schema='public' and table_name=r.table_name) then
      v_missing_tables := array_append(v_missing_tables,r.table_name);
    end if;
  end loop;
  return jsonb_build_object(
    'snapshotId',p_snapshot,'schemaVersion',v_schema,'expectedCurrentVersion','022',
    'schemaCompatible',(v_schema >= '010' and v_schema <= '022'),
    'tableCount',v_tables,'rowCount',v_rows,'badChecksums',v_bad_checksums,
    'missingTables',to_jsonb(v_missing_tables),'valid',(v_schema >= '010' and v_schema <= '022' and v_bad_checksums=0 and cardinality(v_missing_tables)=0)
  );
end
$$;

create or replace function uos_restore_snapshot_as_new_workspace(
  p_snapshot uuid,
  p_new_name text
) returns uuid
language plpgsql security definer set search_path=public as $$
declare
  v_source_workspace uuid;
  v_new_workspace uuid;
  v_run uuid;
  r record;
  v_payload jsonb;
  v_rows bigint := 0;
  v_inserted bigint := 0;
begin
  select workspace_id into v_source_workspace from uos_recovery_snapshots where id=p_snapshot and status='ready';
  if v_source_workspace is null then raise exception 'ready snapshot not found'; end if;
  if not uos_can_manage_workspace(v_source_workspace) then raise exception 'restore requires workspace manager/admin access'; end if;
  if not coalesce((uos_validate_recovery_snapshot(p_snapshot)->>'valid')::boolean,false) then raise exception 'snapshot compatibility validation failed'; end if;

  insert into uos_workspaces(owner_id,name,base_currency)
  select auth.uid(), coalesce(nullif(trim(p_new_name),''),'Restored Workspace'), base_currency
    from uos_workspaces where id=v_source_workspace
  returning id into v_new_workspace;

  insert into uos_recovery_runs(workspace_id,snapshot_id,restored_to_workspace_id,action,actor_id)
  values(v_source_workspace,p_snapshot,v_new_workspace,'restore',auth.uid())
  returning id into v_run;

  -- Parent-first order: tables with fewer outgoing FK dependencies are restored first.
  for r in
    select ri.table_name, ri.payload
      from uos_recovery_items ri
     where ri.snapshot_id=p_snapshot
     order by (
       select count(*) from pg_constraint c
       join pg_class src on src.oid=c.conrelid
       join pg_class dst on dst.oid=c.confrelid
      where src.relname=ri.table_name and dst.relname like 'uos_%' and c.contype='f'
     ) asc, ri.table_name
  loop
    v_payload := coalesce((select jsonb_agg(jsonb_set(x,'{workspace_id}',to_jsonb(v_new_workspace),true)) from jsonb_array_elements(r.payload) x),'[]'::jsonb);
    v_rows := jsonb_array_length(v_payload);
    execute format('insert into %I select * from jsonb_populate_recordset(null::%I, $1::jsonb)',r.table_name,r.table_name) using v_payload;
    v_inserted := v_inserted + v_rows;
  end loop;

  update uos_recovery_runs set status='success', completed_at=now(), summary=jsonb_build_object('newWorkspaceId',v_new_workspace,'rows',v_inserted) where id=v_run;
  update uos_recovery_snapshots set status='restored', restored_to_workspace_id=v_new_workspace where id=p_snapshot;
  return v_new_workspace;
exception when others then
  if v_run is not null then
    update uos_recovery_runs set status='failed', completed_at=now(), error=sqlerrm, summary=jsonb_build_object('newWorkspaceId',v_new_workspace) where id=v_run;
  end if;
  if v_new_workspace is not null then
    delete from uos_workspaces where id=v_new_workspace and owner_id=auth.uid();
  end if;
  raise;
end
$$;

create or replace function uos_rollback_restored_workspace(p_workspace uuid)
returns boolean
language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from uos_workspaces where id=p_workspace and owner_id=auth.uid()) then
    raise exception 'only the restored workspace owner can rollback it';
  end if;
  delete from uos_workspaces where id=p_workspace and owner_id=auth.uid();
  return true;
end
$$;

create or replace function uos_recovery_context(p_workspace uuid)
returns jsonb language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'workspaceId',p_workspace,
    'role',uos_workspace_role(p_workspace),
    'canRead',uos_can_read_workspace(p_workspace),
    'canManage',uos_can_manage_workspace(p_workspace),
    'currentSchemaVersion',(select current_version from uos_schema_registry where id=true),
    'minimumCompatibleVersion',(select minimum_compatible_version from uos_schema_registry where id=true)
  )
$$;
